//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Manual changes made: Ranges and StringLength added.
namespace Veikkausliigapalvelu.Models
{
    using System.ComponentModel.DataAnnotations;
    
    public partial class LeagueTable
    {
        public int TeamID { get; set; }
        public int Matches { get; set; }
        public int GoalDifference { get; set; }
        public int Points { get; set; }
        public string TeamLogoUrl { get; set; }

        [StringLength(20)]
        public string TeamName { get; set; }
  
        [Range(0, 50)]
        public int Wins { get; set; }
        
        [Range(0, 50)]
        public int Draws { get; set; }
        
        [Range(0, 50)]
        public int Loses { get; set; }
        
        [Range(0, 200)]
        public int GoalsFor { get; set; }
        
        [Range(0, 200)]
        public int GoalsAgaints { get; set; }        
    }
}