//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veikkausliigapalvelu.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Veikkausliigapalvelu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virhe! Ottelutietoja ei löydy..
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Message: .
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string Hyphen {
            get {
                return ResourceManager.GetString("Hyphen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iltalehti.
        /// </summary>
        internal static string IL {
            get {
                return ResourceManager.GetString("IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iltasanomat.
        /// </summary>
        internal static string IS {
            get {
                return ResourceManager.GetString("IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content\\Files\\leaguetable.json.
        /// </summary>
        internal static string LeagueTableJsonPath {
            get {
                return ResourceManager.GetString("LeagueTableJsonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content\\Files\\matches.json.
        /// </summary>
        internal static string MatchesJsonPath {
            get {
                return ResourceManager.GetString("MatchesJsonPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mtvsport.
        /// </summary>
        internal static string MTV {
            get {
                return ResourceManager.GetString("MTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otteluita ei löytynyt päiviltä .
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content\\Sliders.
        /// </summary>
        internal static string SlidersPath {
            get {
                return ResourceManager.GetString("SlidersPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.iltalehti.fi/rss/jalkapallo.xml.
        /// </summary>
        internal static string url_IL {
            get {
                return ResourceManager.GetString("url_IL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.iltasanomat.fi/rss/veikkausliiga.xml.
        /// </summary>
        internal static string url_IS {
            get {
                return ResourceManager.GetString("url_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.mtv.fi/api/feed/rss/urheilu_futis.
        /// </summary>
        internal static string url_MTV {
            get {
                return ResourceManager.GetString("url_MTV", resourceCulture);
            }
        }
    }
}
